config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'home#index'
  devise_for :user

  resources :users do
    resources :jobs
  end
  resources :personal_messages, only: [:new ,:create]
  resources :conversations, only: [:index, :show]
  resources :categories, only: [:index]

  get 'categories/:id/subcategories' => 'categories#show_subcategories', :as => 'subcategories'
  get '/search' => 'jobs#search', :as => 'search_page'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'about', :to => 'about#index'
  get 'home', :to => 'home#index'
  get 'jobs', :to => 'jobs#index'
  get 'contact', :to => 'contact#index'
  get 'faq', :to=> 'faq#index'
  get 'location', :to=> 'location#index'
  get 'social', :to=> 'social#index'
  get 'privacy', :to=> 'privacy#index'
  get 'terms', :to=> 'terms#index'
  get 'manage store', :to => 'users#index'
  get 'job/:id', :to => 'jobs#show', :as => 'job_detail'
  get 'billing', :to => 'billing#index'
  get 'billing/card/new' => 'billing#new_card', :as => 'add_payment_method'
  get 'billing/card/delete/:id' => 'billing#destroy', :as => 'delete_card'
  post 'billing/card' => "billing#create_card", as: :create_payment_method
  get 'billing/success' => 'billing#success', as: :success
  get 'billing/success_message' => 'billing#success_message', as: :success_message
  get 'jobs/order/:id' => "jobs#new_order", as: :new_order
  get 'user/:id/orders' => "orders#index", as: :user_orders
  delete 'user/:id/orders/:id' => "orders#destroy", as: :delete_user_order
  if Rails.env.production?
    get '404', to: 'application#page_not_found'
    get '422', to: 'application#server_error'
    get '500', to:  'application#server_error'
  end

end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :user
  belongs_to :subcategory

  validates :name, presence: true
  validates :subcategory_id, presence: true
  validates :cost, presence: true
  validates :description, presence: true
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_user

  def index
    if(params[:cid])
      @jobs = Job.all.where(:subcategory => params[:cid])
    else
      @jobs = Job.all
    end
  end

  def show
    @job = Job.find(params[:id])
  end

  def new
    @job = @user.jobs.new
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    if @job.update(jobs_param)
      redirect_to users_path
    else
      render 'edit'
    end
  end

  def delete_job(jobid)
    str_id = Job.find(jobid).stripe_id
    jobv = Stripe::SKU.retrieve(str_id)
    prd_id = jobv["product"]
    Stripe::SKU.delete(jobv["id"])
    Stripe::Product.delete(prd_id)
  end

  def create_job(jobid)
    @job = Job.find(jobid)
    respond_to do |format|
      if current_user.stripe_id.nil?
        customer = Stripe::Customer.create({"email": current_user.email})
        #here we are creating a stripe customer with the help of the Stripe library and pass as parameter email.
        current_user.update(:stripe_id => customer.id)
        #we are updating current_user and giving to it stripe_id which is equal to id of customer on Stripe
      end
      if @job.stripe_id.nil?
        productv = Stripe::Product.create({
          name: @job.name,
          type: 'good',
          description: @job.description,
          })
        productv.save
        #here we are creating a stripe customer with the help of the Stripe library and pass as parameter email.
        jobv = Stripe::SKU.create({
          currency: 'cad',
          inventory: {
            'type' => 'infinite'
          },
          price: @job.cost.to_i,
          product: productv.id
        })
        @job.update(:stripe_id => jobv.id)
        #we are updating current_user and giving to it stripe_id which is equal to id of customer on Stripe
      end

      jobtoken = params[:stripeToken]
      #it's the stripeToken that we added in the hidden input
      if jobtoken.nil?
        format.html { redirect_to jobs_path, error: "Oops"}
      end
      #checking if a job was giving.
      jobv = Stripe::SKU.new @job.stripe_id
      jobv.save
    end
  end

  def create
    @job = Job.new(jobs_param)
    @user = params[:user_id]
    @subcategory = params[:job][:subcategory_id]
    @job.user_id = @user
    @job.subcategory_id = @subcategory
    if @job.save
      create_job(@job.id)
    else
      render 'new'
    end
  end

  def new_order
    if current_user.stripe_id.nil?
      customer = Stripe::Customer.create({"email": current_user.email})
      #here we are creating a stripe customer with the help of the Stripe library and pass as parameter email.
      current_user.update(:stripe_id => customer.id)
      #we are updating current_user and giving to it stripe_id which is equal to id of customer on Stripe
    end
    @job = params[:id]
    str_id = Job.find(@job).stripe_id
    Stripe::Order.create({
      currency: 'cad',
      email: current_user.email,
      items: [
        {type: 'sku', parent: str_id},
      ],
      shipping: {
        name: current_user.fname+' '+current_user.lname,
        address: {
          line1: current_user.street,
          city: current_user.city,
          state: current_user.province,
          country: 'CA',
          postal_code: current_user.postalCode,
        },
      },
    })
    @ongoing = OngoingTask.new({job_id: @job, user_id: current_user.id, status: "ongoing"})
    @ongoing.save
    @order = Order.new({job_id: @job, user_id: Job.find(@job).user_id, customer_id: current_user.id, status: 0, amount: Job.find(@job).cost})
    @order.save
    redirect_to success_message_path
  end

  def search
    if params[:search].blank?
      redirect_to(root_path, alert: "Empty field!") and return
    else
      @parameter = params[:search].downcase
      @results = Job.all.where("lower(jobs.name) LIKE :search ", search: "%#{@parameter}%")
    end
  end


  def destroy
    @job = Job.find(params[:id])
    delete_job(@job.id)
    @job.destroy
    redirect_to users_path
  end

  private
    def jobs_param
      params.require(:job).permit(:name, :cost, :description, :subcategory_id)
    end
    def set_user
      @user = current_user
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/edit.html.erb
<div class="newjob">
  <br/>
  <h2>Edit Job</h2>
  <%= form_for :job, :url => user_job_path(current_user, @job), method: :patch do |f| %>
    <div class="field">
      <b><%= f.label :name %><br /> </b>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <b><%= f.label :subcategory_id %><br /> </b>
      <%= f.select :subcategory_id, Subcategory.pluck(:name, :category_id)%>
    </div>
    <br/>
    <div class="field">
      <b><%= f.label :cost %><br /> </b>
      <%= f.number_field :cost, min:1 %>
    </div>
    <br/>
    <div class="field">
      <b><%= f.label :description %><br /> </b>
      <%= f.text_area :description %>
    </div>
    <br/>
    <div class="actions">
      <b> <%= f.submit "Update" %> </b>
    </div>
  <% end %>
</div>

app/views/jobs/index.html.erb
<% @jobs.each do |job| %>
  <div class="eachjob spring-fever">
    <div class="title-content">
      <h3><%= job.name %></h3>
      <hr />
      <div class="intro"><%= Category.find(Subcategory.find(job.subcategory_id).category_id).name %></div>
      <div class="intro"><%= Subcategory.find(job.subcategory_id).name %></div>
    </div><!-- /.title-content -->
    <div class="card-info">
      Find More: <%= link_to 'Details', job_detail_path(job) %> <br/>
      <%= job.description %> <br/>
    </div><!-- /.card-info -->
    <div class="utility-info">
      <ul class="utility-list">
        <li class="usersicon"> <%= image_tag("user.jpg", :alt => "user", style: "height: 100%;")%><b> User: <%= User.find(job.user_id).fname %></b></li>
        <li class="date" style="padding-left: 10%"><%= job.created_at.to_date %></li>
      </ul>
    </div><!-- /.utility-info -->
    <!-- overlays -->
    <div class="gradient-overlay"></div>
    <div class="color-overlay"></div>
  </div><!-- /.blog-card -->
<% end %>

app/views/jobs/new.html.erb
<div class="newjob">
  <br/>
  <h2>Create a job</h2>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@job.errors.count, "error") %> prohibited
        this job from being saved:
      </h2>
      <ul>
        <% @job.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_for :job, :url => user_jobs_path(@user, @job) do |f| %>
    <div class="field">
      <b><%= f.label :name %><br /> </b>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <b><%= f.label :subcategory_id %><br /> </b>
      <%= f.select :subcategory_id, Subcategory.pluck(:name, :id)%>
    </div>
    <br/>
    <div class="field">
      <b><%= f.label :cost %><br /> </b>
      <%= f.number_field :cost, min:1 %>
    </div>
    <br/>
    <div class="description">
      <b><%= f.label :description %><br /> </b>
      <%= f.text_area :description %>
    </div>
    <br/>
    <div class="actions">
      <b> <%= f.submit "Create" %> </b>
    </div>
  <% end %>
</div>

app/views/jobs/search.html.erb
<div style="margin-left:5vw; margin-right:5vw; margin-bottom:5vh;">
  <h3 style="padding-top:5vh;">Search Result</h3>  
  <form>
    <input type="button" value="Go back" onclick="history.back()">
  </form>

  <div style="margin-bottom:60vh;">
    <% @results.each do |job| %>
      <div class="eachjob spring-fever">
        <div class="title-content">
          <h3><%= job.name %></h3>
          <hr />
          <div class="intro"><%= Category.find(Subcategory.find(job.subcategory_id).category_id).name %></div>
          <div class="intro"><%= Subcategory.find(job.subcategory_id).name %></div>
        </div><!-- /.title-content -->
        <div class="card-info">
          <%= job.description %> <br/>
          Find More: <%= link_to 'Details', job_detail_path(job) %>
        </div><!-- /.card-info -->
        <div class="utility-info">
          <ul class="utility-list">
            <li class="usersicon" style="padding-left: 25%"><b><%= User.find(job.user_id).fname %></b></li>
            <li class="date" style="padding-left: 10%"><%= job.created_at.to_date %></li>
          </ul>
        </div><!-- /.utility-info -->
        <!-- overlays -->
        <div class="gradient-overlay"></div>
        <div class="color-overlay"></div>
      </div><!-- /.blog-card -->
    <% end %>
  </div>

</div>

    