config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'home#index'
  devise_for :user

  resources :users do
    resources :jobs
  end
  resources :personal_messages, only: [:new ,:create]
  resources :conversations, only: [:index, :show]
  resources :categories, only: [:index]

  get 'categories/:id/subcategories' => 'categories#show_subcategories', :as => 'subcategories'
  get '/search' => 'jobs#search', :as => 'search_page'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'about', :to => 'about#index'
  get 'home', :to => 'home#index'
  get 'jobs', :to => 'jobs#index'
  get 'contact', :to => 'contact#index'
  get 'faq', :to=> 'faq#index'
  get 'location', :to=> 'location#index'
  get 'social', :to=> 'social#index'
  get 'privacy', :to=> 'privacy#index'
  get 'terms', :to=> 'terms#index'
  get 'manage store', :to => 'users#index'
  get 'job/:id', :to => 'jobs#show', :as => 'job_detail'
  get 'billing', :to => 'billing#index'
  get 'billing/card/new' => 'billing#new_card', :as => 'add_payment_method'
  get 'billing/card/delete/:id' => 'billing#destroy', :as => 'delete_card'
  post 'billing/card' => "billing#create_card", as: :create_payment_method
  get 'billing/success' => 'billing#success', as: :success
  get 'billing/success_message' => 'billing#success_message', as: :success_message
  get 'jobs/order/:id' => "jobs#new_order", as: :new_order
  get 'user/:id/orders' => "orders#index", as: :user_orders
  delete 'user/:id/orders/:id' => "orders#destroy", as: :delete_user_order
  if Rails.env.production?
    get '404', to: 'application#page_not_found'
    get '422', to: 'application#server_error'
    get '500', to:  'application#server_error'
  end

end

app/models/category.rb
class Category < ApplicationRecord
	has_many :subcategories
end

app/models/contact.rb
class Contact < ActiveRecord::Base

    validates :email, 
      :presence => :true,
      :format => { 
        :with => /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i,
        :message => "must be a valid email address"
      }
    validates :message, :presence => :true
  
  end

app/models/conversation.rb
class Conversation < ApplicationRecord
	belongs_to :author, class_name: 'User'
	belongs_to :receiver, class_name: 'User'
	validates :author, uniqueness: {scope: :receiver}
	has_many :personal_messages, -> { order(created_at: :asc) }, dependent: :destroy

	scope :participating, -> (user) do
		where("(conversations.author_id = ? OR conversations.receiver_id = ?)", user.id, user.id)
  end

    scope :between, -> (sender_id, receiver_id) do
      where(author_id: sender_id, receiver_id: receiver_id).or(where(author_id: receiver_id, receiver_id: sender_id)).limit(1)
    end

	def with(current_user)
	  author == current_user ? receiver : author
	end  

	def participates?(user)
	  author == user || receiver == user
    end
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :user
  belongs_to :subcategory

  validates :name, presence: true
  validates :subcategory_id, presence: true
  validates :cost, presence: true
  validates :description, presence: true
end

app/models/ongoing_task.rb
class OngoingTask < ApplicationRecord
  belongs_to :user
  belongs_to :job
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
	belongs_to :category
	has_many :jobs
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :jobs
  has_many :wallets
  has_many :authored_conversations, class_name: 'Conversation', foreign_key: 'author_id'
  has_many :received_conversations, class_name: 'Conversation', foreign_key: 'receiver_id'
  has_many :personal_messages, dependent: :destroy
end

app/controllers/billing_controller.rb
class BillingController < ApplicationController
  before_action :authenticate_user!

  def index
    @user=current_user
    if current_user.stripe_id.nil?
      customer = Stripe::Customer.create({"email": current_user.email})
      #here we are creating a stripe customer with the help of the Stripe library and pass as parameter email.
      current_user.update(:stripe_id => customer.id)
      #we are updating current_user and giving to it stripe_id which is equal to id of customer on Stripe
    end
    @customer = Stripe::Customer.list({email: current_user.email})
    @cards = Stripe::Customer.list_sources(@customer['data'][0]['id'], {object: 'card'},)
  end

  def new_card
    respond_to do |format|
      format.js
    end
  end

  def success_message
  end

  def create_card
    respond_to do |format|
      if current_user.stripe_id.nil?
        customer = Stripe::Customer.create({"email": current_user.email})
        #here we are creating a stripe customer with the help of the Stripe library and pass as parameter email.
        current_user.update(:stripe_id => customer.id)
        #we are updating current_user and giving to it stripe_id which is equal to id of customer on Stripe
      end

      card_token = params[:stripeToken]
      #it's the stripeToken that we added in the hidden input
      if card_token.nil?
        format.html { redirect_to billing_path, error: "Oops"}
      end
      #checking if a card was giving.

      customer = Stripe::Customer.new current_user.stripe_id
      customer.source = card_token
      #we're attaching the card to the stripe customer
      customer.save

      format.html { redirect_to success_path }
    end
  end

  def destroy
    @customer = Stripe::Customer.list({email: current_user.email})
    @card = params[:id]
    Stripe::Customer.delete_source(
      @customer['data'][0]['id'],
      @card,
    )
    redirect_to billing_path
  end

  def success
    redirect_to billing_path
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/billing_helper.rb
module BillingHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/location_helper.rb
module LocationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/privacy_helper.rb
module PrivacyHelper
end

app/helpers/social_helper.rb
module SocialHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wallet_helper.rb
module WalletHelper
end

app/views/billing/index.html.erb
<div class="log-in" style="margin-bottom:20vh;">
  <h4> Hello <%= @user.fname %> </h4>
  <p> The following cards exist for you: </p>
  <div style="text-align: left; margin-left: 10%;">
    <% @cards.each do |card| %>
       <h5> <li> Card information: </li> </h5>
       <h7> <b>Ending With: </b>**** **** **** **** <%= card["last4"] %> </h7> <br/>
       <h7> <b>Type: </b><%= card["funding"] %> </h7> <br/>
       <h7> <b>Expiring: </b><%= card["exp_month"] %>, <%= card["exp_year"] %> </h7>
       <%= link_to "Delete Card", delete_card_path(card["id"]) %>
    <% end %>
  </div>
  <div class="row">
    <div class="col-md-12 mt-4 text-center">
      <%= form_tag create_payment_method_path, id: "billing-create-payment-method" do  %>
        <%= link_to "Add a new card", add_payment_method_path, :remote => true, class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/billing/new_card.js.erb
var handler = StripeCheckout.configure({
    key: '<%= ENV['STRIPE_PUBLISHABLE_KEY'] %>',
    //get a publishable key that we put in editor depending on environment: production or development
    locale: 'auto',
    //handle translation
    name: "upload.express",
    description: "Add your credit card information",
    email: "<%= current_user.email %>",
    panelLabel: "Add payment method",
    allowRememberMe: false,
    token: function (token) {
        var form = document.getElementById('billing-create-payment-method');
        //we will create element with this id in the next step
        var hiddenInput = document.createElement('input');
        hiddenInput.setAttribute('type', 'hidden');
        hiddenInput.setAttribute('name', 'stripeToken');
        hiddenInput.setAttribute('value', token.id);
        //creating an <input type="hidden" name="stripeToken" value="<id>"/>. We will need this information in the next steps to link a user to his card
        form.appendChild(hiddenInput);
        //adding this input when we use a form.
        form.submit();
    }
});

handler.open();

window.addEventListener('popstate', function() {
    handler.close();
});

app/views/billing/success_message.html.erb
<style>
  .wrapper {
    position: relative;
    perspective: 40em;
    display: grid;
    transform-style: preserve-3d;
  }

  .card {
    margin-top: 10%;
    margin-bottom: 15%;
    margin-left: 21vw;
    grid-area: 1 / 1;
    height: 60vh;
    width: 50vw;
    transform: translateX(10px) rotateY(25deg) rotateX(10deg);
    background: rgba(249, 198, 26, 0.88);
    display: flex;
    justify-content: flex-start;
    align-items: center;
    padding: 30px;
    color: #000;
    text-transform: uppercase;
    font-size: 60px;
    font-weight: 900;
    backface-visibility: hidden;
    box-shadow: 0 10px 30px -3px rgba(0,0,0,.1);
  }

  h1 {
    font-size: 60px;
    font-weight: 900;
  }

  .card .enclosed {
    background: #000;
    line-height: 1;
    color: rgba(249, 198, 26, 1);
    padding: 0 5px;
    margin-top: 13vh;
    margin-bottom: 10%;
    margin-right: 3%;
    display: inline-block;
    transform: translate(-1px, 1px) scale(0.75);
    transform-origin: right center;
  }

  .wrapper:before {
    --bw: 9px;
    grid-area: 1 / 1;
    content: '';
    backface-visibility: hidden;
    height: 70%;
    width: 51%;
    margin-top: 10vh;
    margin-left: 20vw;
    background: transparent;
    transform: translateX(-60px) rotateY(-30deg) rotateX(15deg) scale(1.03);
    pointer-events: none;
    border: var(--bw) solid #000;
    box-sizing: content-box;
  }


  .wrapper:hover > div,
  .wrapper:hover:before {
    transform: none;
  }


  .wrapper > div,
  .wrapper:before {
    will-change: transform;
    transition: .3s transform cubic-bezier(.25,.46,.45,1);
  }

</style>
<div class="wrapper">
  <div class="card">
    <h1>
      <span class="enclosed">Order Successful</span>
      <div class="row">
        <div class="col-md-12 mt-4 text-center">
          <%= form_tag id: "billing-sign-in" do  %>
            <%= link_to "View All Orders", user_orders_path(current_user) %>
          <% end %>
        </div>
      </div>
    </h1>
  </div>
</div>