config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'home#index'
  devise_for :user

  resources :users do
    resources :jobs
  end
  resources :personal_messages, only: [:new ,:create]
  resources :conversations, only: [:index, :show]
  resources :categories, only: [:index]

  get 'categories/:id/subcategories' => 'categories#show_subcategories', :as => 'subcategories'
  get '/search' => 'jobs#search', :as => 'search_page'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'about', :to => 'about#index'
  get 'home', :to => 'home#index'
  get 'jobs', :to => 'jobs#index'
  get 'contact', :to => 'contact#index'
  get 'faq', :to=> 'faq#index'
  get 'location', :to=> 'location#index'
  get 'social', :to=> 'social#index'
  get 'privacy', :to=> 'privacy#index'
  get 'terms', :to=> 'terms#index'
  get 'manage store', :to => 'users#index'
  get 'job/:id', :to => 'jobs#show', :as => 'job_detail'
  get 'billing', :to => 'billing#index'
  get 'billing/card/new' => 'billing#new_card', :as => 'add_payment_method'
  get 'billing/card/delete/:id' => 'billing#destroy', :as => 'delete_card'
  post 'billing/card' => "billing#create_card", as: :create_payment_method
  get 'billing/success' => 'billing#success', as: :success
  get 'billing/success_message' => 'billing#success_message', as: :success_message
  get 'jobs/order/:id' => "jobs#new_order", as: :new_order
  get 'user/:id/orders' => "orders#index", as: :user_orders
  delete 'user/:id/orders/:id' => "orders#destroy", as: :delete_user_order
  if Rails.env.production?
    get '404', to: 'application#page_not_found'
    get '422', to: 'application#server_error'
    get '500', to:  'application#server_error'
  end

end

app/models/category.rb
class Category < ApplicationRecord
	has_many :subcategories
end

app/models/contact.rb
class Contact < ActiveRecord::Base

    validates :email, 
      :presence => :true,
      :format => { 
        :with => /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i,
        :message => "must be a valid email address"
      }
    validates :message, :presence => :true
  
  end

app/models/conversation.rb
class Conversation < ApplicationRecord
	belongs_to :author, class_name: 'User'
	belongs_to :receiver, class_name: 'User'
	validates :author, uniqueness: {scope: :receiver}
	has_many :personal_messages, -> { order(created_at: :asc) }, dependent: :destroy

	scope :participating, -> (user) do
		where("(conversations.author_id = ? OR conversations.receiver_id = ?)", user.id, user.id)
  end

    scope :between, -> (sender_id, receiver_id) do
      where(author_id: sender_id, receiver_id: receiver_id).or(where(author_id: receiver_id, receiver_id: sender_id)).limit(1)
    end

	def with(current_user)
	  author == current_user ? receiver : author
	end  

	def participates?(user)
	  author == user || receiver == user
    end
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :user
  belongs_to :subcategory

  validates :name, presence: true
  validates :subcategory_id, presence: true
  validates :cost, presence: true
  validates :description, presence: true
end

app/models/ongoing_task.rb
class OngoingTask < ApplicationRecord
  belongs_to :user
  belongs_to :job
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
	belongs_to :category
	has_many :jobs
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :jobs
  has_many :wallets
  has_many :authored_conversations, class_name: 'Conversation', foreign_key: 'author_id'
  has_many :received_conversations, class_name: 'Conversation', foreign_key: 'receiver_id'
  has_many :personal_messages, dependent: :destroy
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show_subcategories
    @categories = Category.where(:id => params[:id])
    @subcategories = Subcategory.all.where(:category => params[:id])
  end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/billing_helper.rb
module BillingHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/location_helper.rb
module LocationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/privacy_helper.rb
module PrivacyHelper
end

app/helpers/social_helper.rb
module SocialHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wallet_helper.rb
module WalletHelper
end

app/views/categories/index.html.erb
<!DOCTYPE html>
<html>
    <head>
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
        <style>
        </style>
    </head>
    <body>
        <div style="margin-left:5vw; margin-right:5vw; margin-bottom:50vh;">
          <h2 style="padding-top:6vh;">Categories</h2>
          <div class="row" style="padding-bottom:20vh; display:inline;">
            <% @categories.each do |c| %>
              <div class="card border-info">
                <div class="card body"><h3><%= link_to c.name, subcategories_path(c) %></h3></div>
              </div>
            <% end %>
          </div>
        </div>
    </body>
</html>

app/views/categories/show_subcategories.html.erb
<!DOCTYPE html>
<html>
    <head>
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
        <style>
        </style>
    </head>
    <body>
        <div style="margin-left:5vw; margin-right:5vw; margin-bottom:50vh;">
          <h2 style="padding-top:6vh;">
            <% @categories.each do |c| %>
              <%= c.name %>
            <% end %>
          </h2>
          <div class="row" style="padding-bottom:20vh; display:inline;">
            <% @subcategories.each do |s| %>
              <div class="card border-info">
                <div class="card body"><h3><%= link_to s.name, jobs_path(cid: s.id) %></h3></div>
              </div>
            <% end %>
          </div>
        </div>
    </body>
</html>